export const styles = {
  container: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    height: '100vh',
    backgroundColor: '#121212',
    color: '#e0e0e0',
    fontFamily: 'sans-serif',
  },
  form: {
    display: 'flex',
    flexDirection: 'column' as const,
    backgroundColor: '#1e1e1e',
    padding: '40px',
    borderRadius: '6px',
    boxShadow: '0 4px 12px rgba(0,0,0,0.5)',
    width: '320px',
    border: '1px solid #2d2d2d',
  },
  title: {
    textAlign: 'center' as const,
    marginBottom: '24px',
    fontWeight: 500,
    letterSpacing: '0.5px',
  },
  input: {
    padding: '12px',
    marginBottom: '16px',
    borderRadius: '4px',
    border: '1px solid #333',
    backgroundColor: '#252525',
    color: '#fff',
    fontSize: '14px',
    outline: 'none',
  },
  button: {
    padding: '12px',
    borderRadius: '4px',
    border: 'none',
    backgroundColor: '#3a3a3a',
    color: '#fff',
    cursor: 'pointer',
    fontWeight: 'bold' as const,
    fontSize: '14px',
    transition: 'background 0.2s',
    marginBottom: '12px',
  },
  divider: {
    position: 'relative' as const,
    textAlign: 'center' as const,
    margin: '16px 0',
    fontSize: '13px',
    color: '#666',
  },
  googleButton: {
    backgroundColor: '#1f2937',
    border: '1px solid #4b5563',
    marginBottom: '0px',
  },
  message: {
    marginTop: '16px',
    textAlign: 'center' as const,
    fontSize: '14px',
    fontWeight: 500,
  },
  toggleText: {
    marginTop: '20px',
    textAlign: 'center' as const,
    fontSize: '13px',
    color: '#aaaaaa',
  },
  link: {
    color: '#e0e0e0',
    textDecoration: 'underline',
    cursor: 'pointer',
    fontWeight: 500,
  },
};
